import type { Metadata } from 'next';

import { Roboto } from 'next/font/google';
import './globals.css';

import { ReactNode } from 'react';
import MainLayout from '@/app/components/layout/MainLayout';
import Footer from '@/app/components/layout/Footer';
import Contact from '@/app/components/Home/Contact';
import About from '@/app/components/Home/About';
import MainBrief from '@/app/components/Home/MainBrief';

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-sans antialiased`}>
        <MainLayout
          hero={<MainBrief />}
          main={children}
          rightRail={
            <>
              <Contact />
              <About />
            </>
          }
          footer={<Footer />}
        />
      </body>
    </html>
  );
}
